### ISSUE TITLE
Issue when installing new bundles

### ISSUE THREAD

**Issue by estebanrules** [astrails/dotvim#35]
When I try to add a new bundle in the bundles.vim file, every time I restart Vim it asks me if I would like to install that bundle (it isn't installing properly).  Should user added bundles be placed in a different file?

Here is a screenshot:

![screenshot_2014-12-26_15_01_39](https://cloud.githubusercontent.com/assets/4554498/5559168/9f527c54-8d10-11e4-836c-f1c738ba63cd.png)

**Comment by vitaly** [comment]
No. It probably isn't installing because you left out the `.vim` part at the end of the repository name ;)

**Comment by estebanrules** [comment]
So sorry about that, that was indeed the issue ;)
