### ISSUE TITLE
Ubuntu Install

### ISSUE THREAD

**Issue by rocknrollMarc** [astrails/dotvim#36]
Hey Guys,

Im just switching from OSX to Ubuntu and dont have that much knowlege in ubuntu jet. Im having trouble intsalling your vim Distr can you give me a hand, I guess its because vimrc is not in the place were osx has it how to I get this to work.

ROcknroll nd greetings from HAmburg ( derwaterkant)

**Comment by SamuraiT** [comment]
vimrc always should be `$HOME/.vimrc`. I think you have a different problem.

**Comment by vitaly** [comment]
with no specifics, I can not help ;)
