### ISSUE TITLE
encoding bugs

### ISSUE THREAD

**Issue by SamuraiT** [astrails/dotvim#41]
## Problem
When I use macvim and try to write Japanese,  let's say you wrote 'ハロー'  then will show you different character because of endoing error see the example below. While normal vim(terminal vim) works well. 
What do you think is the problem ? 

This is really serious problem especially for whom writes another languages.
* example

![example](http://i.gyazo.com/9d08c9dfec6b37a1c9bdc1f93982efe0.png)

and when I don't include dotvim files, macvim can work correctly

**Comment by SamuraiT** [comment]
I figured out ! 
inside of this file: `/.vim/plugins.vim`

`let g:airline_powerline_fonts=1`

this makes the encoding error somehow. when I comment this out, it worked!

**Comment by SamuraiT** [comment]
but still don't know how it affects this encoding problem

**Comment by vitaly** [comment]
read the README :): https://github.com/astrails/dotvim#installation_note

airline requires patched fonts to work properly.
