### ISSUE TITLE
error with vim-literate-coffeescript

### ISSUE THREAD

**Issue by anquegi** [astrails/dotvim#48]
HI, Thanks for this vim configuration, the problem is I always get this error: 

[neobundle/install] Error installing bundles:
vim-literate-coffeescript

![captura de pantalla de 2015-07-16 17 28 07](https://cloud.githubusercontent.com/assets/2518346/8727447/10581774-2be0-11e5-9514-5aeef1d5d5ab.png)

**Comment by ashleyconnor** [comment]
+1 - Gonna look into it tomorrow - will report a solution if one is found.

**Comment by vitaly** [comment]
well, the problem is simple, the repository is no longer there ;)

I pushed a cached copy at vitaly/vim-literate-coffeescript. update to latest.

**Comment by anquegi** [comment]
ok, thanks
