### ISSUE TITLE
When I paste code to vim from somewhere, code is re-aligned.

### ISSUE THREAD

**Issue by rocLv** [astrails/dotvim#51]
When I copy code from somewhere, and paste to vim, the code will be re-aligned. I mean double indent.
For example, I copy the follow code:
```ruby
def foo
   do_some_thing
end
```
When I paste to vim, it becomes to:
```ruby
def foo
   do_some_thing
      end
````
This behavior really bothers me.

**Comment by vitaly** [comment]
you can either `:set paste` before and `:set nopaste` after you paste, or use graphical mvim as it knows when a paste is a paste and not just a bunch of keypresses.

**Comment by vitaly** [comment]
has nothing to do with dotvim btw, any auto indent in a terminal editor will have the same problem.
