### ISSUE TITLE
delimitMate and rust plugins hang during install

### ISSUE THREAD

**Issue by ketankshukla** [astrails/dotvim#53]
I had to press Ctrl-C to proceed with installing the rest of the plugins. 

Also I get this error when starting Vim: 

Taglist: Exuberant ctags (http://ctags.sf.net) not found in PATH. Plugin is not loaded.

I commented it out from the bundles.vim file and then it was ok.

**Comment by vitaly** [comment]
1) its most probably related to a local problem with github checkouts. works just fine now.

2) indeed, for taglist to work you need to install `ctags`
