### ISSUE TITLE
missing airline theme "light"

### ISSUE THREAD

**Issue by mattyb** [astrails/dotvim#56]
```
Could not resolve airline theme "light". Themes have been migrated to github.com/vim-airline/vim-airline-themes.
Press ENTER or type command to continue
```

**Comment by kitsched** [comment]
Go to your dotvim directory and edit the `bundles.vim` file. Add

`NeoBundle 'vim-airline/vim-airline-themes'`

after the

`NeoBundle 'bling/vim-airline'

line. Save, quit and run `make install` while still in the dotvim directory.

**Comment by HendrikPetertje** [comment]
I suggested a fix with a pull request for this issue some time ago
https://github.com/astrails/dotvim/pull/55

**Comment by HendrikPetertje** [comment]
The actual temporal fix (until the dev merges the now very old pull req) is:

    Vim ~/.vimrc.bundles

And add

    NeoBundle 'bling/vim-airline'

This does not contaminate the dotvim repo and allows you to pull updates without errors

Just save the file and restart vim. it will detect your package and prompt for install.

**Comment by HendrikPetertje** [comment]
@vitaly any news?

**Comment by vitaly** [comment]
merged the fix.

**Comment by vitaly** [comment]
I haven't updated dotvim repo for a while since I worked on dotvim2 ;). see https://github.com/vitaly/dotvim2
While its not yet finished, its already usable, and much more fast and modular. And it upgrades some outdated components too. Come beta-test guys ;)
