### ISSUE TITLE
Disable AutoComplPop

### ISSUE THREAD

**Issue by guillewu** [astrails/dotvim#57]
Is there a way to disable AutoComplPop from .vimrc.before? Or is the only way to comment it out in bundles.vim?
Thanks!

**Comment by kitsched** [comment]
`:AcpDisable` (from [here](https://github.com/vim-scripts/AutoComplPop/blob/master/doc/acp.txt))

**Comment by vitaly** [comment]
or just move to dotvim2 which has YouCompleteMe instead. and its configurable, so you can easily disable it during installation. https://github.com/vitaly/dotvim2
